[project]
name = "tg"
version = "0.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0,<4",
    "argon2-cffi ~= 25.1.0",
    "cryptography ~= 45.0.5",
    "pydantic-settings ~= 2.10.1",
    "pydantic ~= 2.11.7",
    "aiofiles ~= 24.1.0",
    "aiohttp >= 3.12.13,<3.13",
    "orjson >= 3.11.0,<4",
    "sqlalchemy ~= 2.0.41",
    "sqlmodel ~= 0.0.24",
]

[project.optional-dependencies]
# SQL
postgresql = ["asyncpg~=0.30.0"]
mysql = ["asyncmy~=0.2.10"]
oracle = ["oracledb~=3.2.0"]
mssql = ["aioodbc~=0.5.0"]
sqlite = ["aiosqlite~=0.21.0"]

# NoSQL
redis = ["redis~=6.2.0", "hiredis~=3.2.1"]
mongodb = ["pymongo~=4.13.2"]

[dependency-groups]
dev = [
    "ruff >= 0.12.3",
    "deptry~=0.23.0",
    "pyright[nodejs]~=1.1.403",
    "ipykernel",
]

[tool.ruff]
preview = true
line-length = 120
indent-width = 4
src = ["src"]
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "CPY001", "COM812"]
fixable = ["ALL"]
pydocstyle = { convention = 'google' }
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.deptry.per_rule_ignores]
DEP004 = ["redis", "asyncpg"]

[tool.deptry.package_module_name_map]
asyncmy = ["asyncmy"]
oracledb = ["oracledb"]
aioodbc = ["aioodbc"]
aiosqlite = ["aiosqlite"]

[tool.pyright]
pythonPlatform = "All"
pythonVersion = "3.13"
typeCheckingMode = "strict"
include = ["src"]
venvPath = "."
venv = ".venv"
ignore = [
    "C:/**/Python/Python*/Lib", # Ignoring python's libraries
    "C:/**/.vscode",            # Ignoring python's stubs generated by vscode plugin
    '.venv',
]
